import SwiftJavaConfigurationShared
import SwiftJavaJNICore
import SwiftSyntax
import SwiftSyntaxBuilder


package class FFMSwift2KotlinGenerator: FFMSwift2JavaGenerator {

    override func generate() throws {
        try writeSwiftThunkSources()

        // Replace Java export with Kotlin stub generation
        // TODO: make kotlin actually callable 
        try writeKotlinSources()

        try writeSwiftExpectedEmptySources()
    }

    // MARK: - File writing

    public func writeKotlinSources() throws {
        var printer = CodePrinter()
        try writeKotlinSources(printer: &printer)
    }

    public func writeKotlinSources(printer: inout CodePrinter) throws {

        // One .kt file per imported nominal type
        for (_, ty) in analysis.importedTypes.sorted(by: { $0.key < $1.key }) {
            let filename = "\(ty.swiftNominal.name).kt"
            printKotlinImportedNominal(&printer, ty)
            _ = try printer.writeContents(
                outputDirectory: javaOutputDirectory,
                javaPackagePath: javaPackagePath,
                filename: filename
            )
        }

        // One .kt file for module-level globals and functions
        let filename = "\(swiftModuleName).kt"
        printKotlinModule(&printer)
        _ = try printer.writeContents(
            outputDirectory: javaOutputDirectory,
            javaPackagePath: javaPackagePath,
            filename: filename
        )
    }

    // MARK: - Module printer

    private func printKotlinModule(_ printer: inout CodePrinter) {
        printer.print("// Generated by jextract-swift")
        printer.print("// Swift module: \(swiftModuleName)")
        printer.print("")
        if !javaPackage.isEmpty {
            printer.print("package \(javaPackage)")
            printer.print("")
        }

        printer.print("object \(swiftModuleName) {")
        printer.indent()
        for decl in analysis.importedGlobalFuncs {
            printKotlinFunctionDecl(&printer, decl)
        }
        for decl in analysis.importedGlobalVariables {
            printKotlinFunctionDecl(&printer, decl)
        }
        printer.outdent()
        printer.print("}")
    }  

    private func printKotlinImportedNominal(_ printer: inout CodePrinter, _ decl: ImportedNominalType) {
        printer.print("// Generated by jextract-swift")
        printer.print("// Swift module: \(swiftModuleName)")
        printer.print("")
        if !javaPackage.isEmpty {
            printer.print("package \(javaPackage)")
            printer.print("")
        }

        let keyword = decl.swiftNominal.isReferenceType ? "class" : "data class"
        printer.print("\(keyword) \(decl.swiftNominal.name) {")
        printer.indent()
        for d in decl.initializers { printKotlinFunctionDecl(&printer, d) }
        for d in decl.variables    { printKotlinFunctionDecl(&printer, d) }
        for d in decl.methods      { printKotlinFunctionDecl(&printer, d) }
        printer.outdent()
        printer.print("}")
    }

    // MARK: - Function declaration printer

    private func printKotlinFunctionDecl(
        _ printer: inout CodePrinter,
        _ decl: ImportedFunc
    ) {
        let sig = decl.functionSignature
        let returnType = mapToKotlinType(sig.result.type)
        let methodName = decl.name.asCamelCase
        let args = sig.parameters.map { p in
            "\(p.parameterName ?? "_"): \(mapToKotlinType(p.type))"
        }.joined(separator: ", ")

        printer.print("fun \(methodName)(\(args)): \(returnType) = TODO(\"Not implemented\")")
    }

    // MARK: - Type mapping 

    func mapToKotlinType(_ type: SwiftType) -> String {
        switch type {

        // Optional
        case .optional(let wrapped):
            return "\(mapToKotlinType(wrapped))?"

        // Void == empty tuple
        case .tuple(let elements) where elements.isEmpty:
            return "Unit"
        
        // Single-element tuple — unwrap
        case .tuple(let elements) where elements.count == 1:
            return mapToKotlinType(elements[0].type)

        // [Element] -> List<Element>
        case .array(let element):
            return "List<\(mapToKotlinType(element))>"

        // Nominal types
        case .nominal(let nominal):
            if nominal.nominalTypeDecl.name == "Void" {
                return "Unit"
            }
            guard let known = nominal.nominalTypeDecl.knownTypeKind else {
                return nominal.nominalTypeDecl.name
            }
            switch known {
                case .int:      return "Long"   
                case .int8:     return "Byte"
                case .int16:    return "Short"
                case .int32:    return "Int"
                case .int64:    return "Long"
                case .uint:     return "ULong"
                case .uint8:    return "UByte"
                case .uint16:   return "UShort"
                case .uint32:   return "UInt"
                case .uint64:   return "ULong"
                case .float:    return "Float"
                case .double:   return "Double"
                case .bool:     return "Boolean"
                case .string:   return "String"
                case .void:     return "Unit"
                default:        return nominal.nominalTypeDecl.name
            }

            case .metatype:
              return "KClass<*>"

            case .function:
              return "Function<*>"

            // Fallback for existential, opaque, composite, generic, multi-tuple
            case .existential, .opaque, .composite, .genericParameter, .tuple:
              return "Any"
            }
        }
    }

    // MARK: - String helpers

    private extension String {
        // Converts snake_case or PascalCase -> camelCase
        var asCamelCase: String {
            guard !isEmpty else { return self }
            if contains("_") {
                let parts = split(separator: "_").map(String.init)
                return (parts.first.map { $0.lowercased() } ?? "")
                    + parts.dropFirst().map { $0.capitalized }.joined()
            }
            return prefix(1).lowercased() + dropFirst()
        }
    } 
    